export const ADD_BOOKMARK ='ADD_BOOKMARK'
export const ADD_CAT = 'ADD_CAT'

export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS'
export const FETCH_BM_CAT_SUCCESS = 'FETCH_BM_CAT_SUCCESS'
export const SET_ACTIVE_MENU ='SET_ACTIVE_MENU'
